services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MODE=standalone
      # - TELEMETRY=true
      # - ENABLE_ID_OBFUSCATION=true
    networks:
      - web
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    restart: unless-stopped

networks:
  web:

volumes:
  caddy_data:
  caddy_config:

